// Builds design tokens (DTCG source in ./tokens) into:
//   dist/tokens.css          CSS custom properties (--qf-*), references preserved
//   dist/tailwind.css        Tailwind v4 @theme mapping utilities onto the CSS variables
//   dist/tokens.json         Resolved nested values (Figma plugins, docs, tests)
//   dist/tokens.flat.json    Resolved flat name → value map (contrast tests)
// The DTCG source files are also the files Tokens Studio for Figma syncs from.
import StyleDictionary from "style-dictionary";

const PREFIX = "qf";

/** Maps a token to its Tailwind v4 theme variable, or null if it is not exposed as a utility. */
function tailwindName(token) {
  const [category, ...rest] = token.path;
  const key = rest.join("-");
  switch (category) {
    case "color":
      return `--color-${key}`;
    case "radius":
      return `--radius-${key}`;
    case "space":
      return key === "unit" ? "--spacing" : null; // Tailwind derives the whole scale from one unit
    case "font": {
      const [kind, ...name] = rest;
      if (kind === "family") return `--font-${name.join("-")}`;
      if (kind === "size") return `--text-${name.join("-")}`;
      if (kind === "line-height") return `--text-${name.join("-")}--line-height`;
      if (kind === "weight") return `--font-weight-${name.join("-")}`;
      return null;
    }
    default:
      return null; // palette, border-width and size stay as CSS variables only
  }
}

StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .map((token) => {
        const name = tailwindName(token);
        return name ? `  ${name}: var(--${PREFIX}-${token.name});` : null;
      })
      .filter(Boolean);
    return [
      "/* Generated by @qf/tokens. Do not edit. */",
      "/* Utilities resolve to the --qf-* variables at runtime, so a journey can re-theme by overriding them. */",
      "@theme inline {",
      "  --color-*: initial; /* remove Tailwind's default palette: only semantic tokens are available */",
      "  --color-white: #fff;",
      "  --color-black: #000;",
      ...lines,
      "}",
      "",
    ].join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "json/flat-name",
  format: ({ dictionary }) =>
    JSON.stringify(
      Object.fromEntries(dictionary.allTokens.map((t) => [t.name, t.$value ?? t.value])),
      null,
      2,
    ) + "\n",
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.tokens.json"],
  usesDtcg: true,
  log: { verbosity: "default" },
  platforms: {
    css: {
      prefix: PREFIX,
      transforms: ["attribute/cti", "name/kebab", "color/css", "fontFamily/css"],
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { outputReferences: true, selector: ":root" },
        },
      ],
    },
    tailwind: {
      transforms: ["attribute/cti", "name/kebab"],
      buildPath: "dist/",
      files: [{ destination: "tailwind.css", format: "css/tailwind-theme" }],
    },
    json: {
      transforms: ["attribute/cti", "name/kebab", "color/css"],
      buildPath: "dist/",
      files: [
        { destination: "tokens.json", format: "json/nested" },
        { destination: "tokens.flat.json", format: "json/flat-name" },
      ],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
